# Generated by Django 3.0.3 on 2020-02-24 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_pcs', models.DecimalField(decimal_places=0, max_digits=3)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('shop_id', models.CharField(max_length=20)),
                ('vip', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=0, max_digits=3)),
                ('price', models.DecimalField(decimal_places=0, max_digits=3)),
                ('shop_id', models.CharField(max_length=20)),
                ('CustomerID', models.DecimalField(decimal_places=0, max_digits=3)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Products')),
            ],
        ),
    ]
