# Generated by Django 3.0.3 on 2020-02-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200224_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='CustomerID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='qty',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='stock_pcs',
            field=models.IntegerField(),
        ),
    ]
